//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_ServiceRecipe.ServiceRecipe {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllFoodName", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecipe")]
    [System.SerializableAttribute()]
    public partial class GetAllFoodName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipes", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecipe")]
    [System.SerializableAttribute()]
    public partial class Recipes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RawMaterial {
            get {
                return this.RawMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.RawMaterialField, value) != true)) {
                    this.RawMaterialField = value;
                    this.RaisePropertyChanged("RawMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipe {
            get {
                return this.RecipeField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipeField, value) != true)) {
                    this.RecipeField = value;
                    this.RaisePropertyChanged("Recipe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipesDelete", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecipe")]
    [System.SerializableAttribute()]
    public partial class RecipesDelete : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRecipe.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFoodName", ReplyAction="http://tempuri.org/IService1/GetAllFoodNameResponse")]
        WindowsFormsApp_ServiceRecipe.ServiceRecipe.GetAllFoodName[] GetAllFoodName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFoodName", ReplyAction="http://tempuri.org/IService1/GetAllFoodNameResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp_ServiceRecipe.ServiceRecipe.GetAllFoodName[]> GetAllFoodNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchFoodName", ReplyAction="http://tempuri.org/IService1/SearchFoodNameResponse")]
        WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes SearchFoodName(string inputfoodname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchFoodName", ReplyAction="http://tempuri.org/IService1/SearchFoodNameResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes> SearchFoodNameAsync(string inputfoodname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFoodName", ReplyAction="http://tempuri.org/IService1/AddFoodNameResponse")]
        void AddFoodName([System.ServiceModel.MessageParameterAttribute(Name="addfoodname")] WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes addfoodname1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFoodName", ReplyAction="http://tempuri.org/IService1/AddFoodNameResponse")]
        System.Threading.Tasks.Task AddFoodNameAsync(WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes addfoodname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateFoodName", ReplyAction="http://tempuri.org/IService1/UpdateFoodNameResponse")]
        void UpdateFoodName([System.ServiceModel.MessageParameterAttribute(Name="updatefoodname")] WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes updatefoodname1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateFoodName", ReplyAction="http://tempuri.org/IService1/UpdateFoodNameResponse")]
        System.Threading.Tasks.Task UpdateFoodNameAsync(WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes updatefoodname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFoodName", ReplyAction="http://tempuri.org/IService1/DeleteFoodNameResponse")]
        void DeleteFoodName(WindowsFormsApp_ServiceRecipe.ServiceRecipe.RecipesDelete foodname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFoodName", ReplyAction="http://tempuri.org/IService1/DeleteFoodNameResponse")]
        System.Threading.Tasks.Task DeleteFoodNameAsync(WindowsFormsApp_ServiceRecipe.ServiceRecipe.RecipesDelete foodname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp_ServiceRecipe.ServiceRecipe.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp_ServiceRecipe.ServiceRecipe.IService1>, WindowsFormsApp_ServiceRecipe.ServiceRecipe.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp_ServiceRecipe.ServiceRecipe.GetAllFoodName[] GetAllFoodName() {
            return base.Channel.GetAllFoodName();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp_ServiceRecipe.ServiceRecipe.GetAllFoodName[]> GetAllFoodNameAsync() {
            return base.Channel.GetAllFoodNameAsync();
        }
        
        public WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes SearchFoodName(string inputfoodname) {
            return base.Channel.SearchFoodName(inputfoodname);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes> SearchFoodNameAsync(string inputfoodname) {
            return base.Channel.SearchFoodNameAsync(inputfoodname);
        }
        
        public void AddFoodName(WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes addfoodname1) {
            base.Channel.AddFoodName(addfoodname1);
        }
        
        public System.Threading.Tasks.Task AddFoodNameAsync(WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes addfoodname) {
            return base.Channel.AddFoodNameAsync(addfoodname);
        }
        
        public void UpdateFoodName(WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes updatefoodname1) {
            base.Channel.UpdateFoodName(updatefoodname1);
        }
        
        public System.Threading.Tasks.Task UpdateFoodNameAsync(WindowsFormsApp_ServiceRecipe.ServiceRecipe.Recipes updatefoodname) {
            return base.Channel.UpdateFoodNameAsync(updatefoodname);
        }
        
        public void DeleteFoodName(WindowsFormsApp_ServiceRecipe.ServiceRecipe.RecipesDelete foodname) {
            base.Channel.DeleteFoodName(foodname);
        }
        
        public System.Threading.Tasks.Task DeleteFoodNameAsync(WindowsFormsApp_ServiceRecipe.ServiceRecipe.RecipesDelete foodname) {
            return base.Channel.DeleteFoodNameAsync(foodname);
        }
    }
}
