//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_ServiceRecipe.ServiceWikiFood {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShowAll", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecipe")]
    [System.SerializableAttribute()]
    public partial class ShowAll : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FoodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoodID {
            get {
                return this.FoodIDField;
            }
            set {
                if ((this.FoodIDField.Equals(value) != true)) {
                    this.FoodIDField = value;
                    this.RaisePropertyChanged("FoodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchAndUpdate", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecipe")]
    [System.SerializableAttribute()]
    public partial class SearchAndUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FoodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoodID {
            get {
                return this.FoodIDField;
            }
            set {
                if ((this.FoodIDField.Equals(value) != true)) {
                    this.FoodIDField = value;
                    this.RaisePropertyChanged("FoodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RawMaterial {
            get {
                return this.RawMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.RawMaterialField, value) != true)) {
                    this.RawMaterialField = value;
                    this.RaisePropertyChanged("RawMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipe {
            get {
                return this.RecipeField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipeField, value) != true)) {
                    this.RecipeField = value;
                    this.RaisePropertyChanged("Recipe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddData", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecipe")]
    [System.SerializableAttribute()]
    public partial class AddData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RawMaterial {
            get {
                return this.RawMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.RawMaterialField, value) != true)) {
                    this.RawMaterialField = value;
                    this.RaisePropertyChanged("RawMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipe {
            get {
                return this.RecipeField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipeField, value) != true)) {
                    this.RecipeField = value;
                    this.RaisePropertyChanged("Recipe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteData", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecipe")]
    [System.SerializableAttribute()]
    public partial class DeleteData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWikiFood.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAllFoods", ReplyAction="http://tempuri.org/IService1/ShowAllFoodsResponse")]
        WindowsFormsApp_ServiceRecipe.ServiceWikiFood.ShowAll[] ShowAllFoods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAllFoods", ReplyAction="http://tempuri.org/IService1/ShowAllFoodsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp_ServiceRecipe.ServiceWikiFood.ShowAll[]> ShowAllFoodsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchFoodName", ReplyAction="http://tempuri.org/IService1/SearchFoodNameResponse")]
        WindowsFormsApp_ServiceRecipe.ServiceWikiFood.SearchAndUpdate SearchFoodName(string input_foodname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchFoodName", ReplyAction="http://tempuri.org/IService1/SearchFoodNameResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp_ServiceRecipe.ServiceWikiFood.SearchAndUpdate> SearchFoodNameAsync(string input_foodname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataFood", ReplyAction="http://tempuri.org/IService1/AddDataFoodResponse")]
        void AddDataFood(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.AddData add_data_food);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataFood", ReplyAction="http://tempuri.org/IService1/AddDataFoodResponse")]
        System.Threading.Tasks.Task AddDataFoodAsync(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.AddData add_data_food);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDataFood", ReplyAction="http://tempuri.org/IService1/UpdateDataFoodResponse")]
        void UpdateDataFood(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.SearchAndUpdate update_data_food);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDataFood", ReplyAction="http://tempuri.org/IService1/UpdateDataFoodResponse")]
        System.Threading.Tasks.Task UpdateDataFoodAsync(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.SearchAndUpdate update_data_food);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteDataFood", ReplyAction="http://tempuri.org/IService1/DeleteDataFoodResponse")]
        bool DeleteDataFood(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.DeleteData delete_data_food);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteDataFood", ReplyAction="http://tempuri.org/IService1/DeleteDataFoodResponse")]
        System.Threading.Tasks.Task<bool> DeleteDataFoodAsync(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.DeleteData delete_data_food);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp_ServiceRecipe.ServiceWikiFood.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp_ServiceRecipe.ServiceWikiFood.IService1>, WindowsFormsApp_ServiceRecipe.ServiceWikiFood.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp_ServiceRecipe.ServiceWikiFood.ShowAll[] ShowAllFoods() {
            return base.Channel.ShowAllFoods();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp_ServiceRecipe.ServiceWikiFood.ShowAll[]> ShowAllFoodsAsync() {
            return base.Channel.ShowAllFoodsAsync();
        }
        
        public WindowsFormsApp_ServiceRecipe.ServiceWikiFood.SearchAndUpdate SearchFoodName(string input_foodname) {
            return base.Channel.SearchFoodName(input_foodname);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp_ServiceRecipe.ServiceWikiFood.SearchAndUpdate> SearchFoodNameAsync(string input_foodname) {
            return base.Channel.SearchFoodNameAsync(input_foodname);
        }
        
        public void AddDataFood(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.AddData add_data_food) {
            base.Channel.AddDataFood(add_data_food);
        }
        
        public System.Threading.Tasks.Task AddDataFoodAsync(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.AddData add_data_food) {
            return base.Channel.AddDataFoodAsync(add_data_food);
        }
        
        public void UpdateDataFood(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.SearchAndUpdate update_data_food) {
            base.Channel.UpdateDataFood(update_data_food);
        }
        
        public System.Threading.Tasks.Task UpdateDataFoodAsync(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.SearchAndUpdate update_data_food) {
            return base.Channel.UpdateDataFoodAsync(update_data_food);
        }
        
        public bool DeleteDataFood(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.DeleteData delete_data_food) {
            return base.Channel.DeleteDataFood(delete_data_food);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDataFoodAsync(WindowsFormsApp_ServiceRecipe.ServiceWikiFood.DeleteData delete_data_food) {
            return base.Channel.DeleteDataFoodAsync(delete_data_food);
        }
    }
}
